[tool.poetry]
name = "wildmatch"
version = "0.0.1"
description = "Wrap pathspec (gitignore-like wildmatch) in a CLI"
authors = ["Emma Doyle <emma@premiscale.com>"]
maintainers = ["Emma Doyle <emma@premiscale.com>"]
license = "GPLv3"
readme = "README.md"
packages = [
  { include = "src" }
]
include = [
  "LICENSE"
]
keywords = [
    "git",
    "gitignore",
    "cli"
]

[tool.poetry.dependencies]
python = "^3.9"
pathspec = "^0.12.0"

[tool.poetry.group.dev.dependencies]
twine = "^5.0.0"
pylint = "^2.17.4"
pre-commit = "^3.0.0"
mypy = "^1.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
wildmatch = "src.wildmatch.filter:main"

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true